/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 02-1月-2020 18:18:38 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
;
/* Drop Tables */

DROP TABLE IF EXISTS `message_record` CASCADE
;

DROP TABLE IF EXISTS `order_cancel_record` CASCADE
;

DROP TABLE IF EXISTS `order_change_record` CASCADE
;

DROP TABLE IF EXISTS `order_child` CASCADE
;

DROP TABLE IF EXISTS `order_refund_record` CASCADE
;

DROP TABLE IF EXISTS `orders` CASCADE
;

DROP TABLE IF EXISTS `request_log_month` CASCADE
;

DROP TABLE IF EXISTS `ticket_child` CASCADE
;

DROP TABLE IF EXISTS `withdraw_serial` CASCADE
;

DROP TABLE IF EXISTS `withdraw_limit` CASCADE
;

DROP TABLE IF EXISTS `withdraw_record` CASCADE
;


/* Create Tables */

CREATE TABLE `message_record`
(
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `queue_name` VARCHAR(50) NULL DEFAULT '' COMMENT '队列名称',
  `type` TINYINT NULL DEFAULT 1 COMMENT '消息类型 1 接收消息  2  发送消息',
  `body` TEXT NULL  COMMENT '消息体',
  CONSTRAINT `PK_message_record` PRIMARY KEY (`id` ASC)
)
  COMMENT = '消息记录表'

;

CREATE TABLE `order_cancel_record`
(
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NULL DEFAULT -1 COMMENT '订单id',
  `order_no` VARCHAR(32) NULL DEFAULT '' COMMENT '订单号',
  `cancel_time` DATETIME NULL COMMENT '取消时间',
  `cancel_type` TINYINT NULL DEFAULT 1 COMMENT '取消类型 1 订单支付超时自动取消 2 用户自动取消订单',
  `cancel_reason` VARCHAR(50) NULL DEFAULT '' COMMENT '取消原因',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  CONSTRAINT `PK_order_cancel_record` PRIMARY KEY (`id` ASC)
)
  COMMENT = '订单取消记录表'

;

CREATE TABLE `order_change_record`
(
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NULL DEFAULT -1 COMMENT '订单id',
  `order_no` VARCHAR(50) NULL DEFAULT '' COMMENT '订单号',
  `change_field` VARCHAR(50) NULL DEFAULT '' COMMENT '更改的字段',
  `old_value` VARCHAR(50) NULL DEFAULT '' COMMENT '旧的值',
  `new_value` VARCHAR(50) NULL DEFAULT '' COMMENT '新的值',
  `change_reason` VARCHAR(50) NULL DEFAULT '' COMMENT '更改原因',
  `change_time` DATETIME NULL COMMENT '更改时间',
  CONSTRAINT `PK_order_change_record` PRIMARY KEY (`id` ASC)
)
  COMMENT = '订单更新记录'

;

CREATE TABLE `order_child`
(
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NULL DEFAULT -1 COMMENT '订单id',
  `order_no` VARCHAR(32) NULL DEFAULT '' COMMENT '订单号',
  `goods_id` BIGINT NULL DEFAULT -1 COMMENT '商品id',
  `goods_name` VARCHAR(20) NULL DEFAULT '' COMMENT '商品名称',
  `goods_price` DECIMAL(10,2) NULL COMMENT '商品价格',
  `sku_id` BIGINT NULL DEFAULT -1 COMMENT '商品skuId',
  `sku_name` VARCHAR(50) NULL DEFAULT '',
  `refund_status` TINYINT NULL DEFAULT 1 COMMENT '退款状态 1 不退款  2退款中 3 退款失败 4 退款成功',
  `amount` INT NULL COMMENT '商品购买数量',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  CONSTRAINT `PK_order_child` PRIMARY KEY (`id` ASC)
)
  COMMENT = '子订单 表'

;

CREATE TABLE `order_refund_record`
(
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `child_order_id` BIGINT NULL DEFAULT -1 COMMENT '子订单id',
  `order_id` BIGINT NULL DEFAULT -1 COMMENT '订单id',
  `refund_reason` VARCHAR(50) NULL DEFAULT '' COMMENT '退款原因',
  `refund_price` DECIMAL(10,2) NULL COMMENT '退款金额',
  `refund_status` TINYINT NULL DEFAULT 1 COMMENT '1 发起退款 2退款中 3 退款成功 4 退款失败',
  `order_no` VARCHAR(50) NULL DEFAULT '' COMMENT '订单号',
  `refund_no` VARCHAR(50) NULL DEFAULT '' COMMENT '退款流水号',
  `refund_time` DATETIME NULL COMMENT '退款时间',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  CONSTRAINT `PK_order_refund_record` PRIMARY KEY (`id` ASC)
)
  COMMENT = '订单退单记录'

;

CREATE TABLE `orders`
(
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `member_id` BIGINT NULL DEFAULT -1 COMMENT '会员Id',
  `member_name` VARCHAR(30) NULL DEFAULT '' COMMENT '会员昵称',
  `order_no` VARCHAR(32) NULL DEFAULT '' COMMENT '订单号',
  `three_order_no` VARCHAR(32) NULL DEFAULT '' COMMENT '第三方订单号',
  `partner_id` BIGINT NULL DEFAULT -1 COMMENT '合作方id',
  `type` TINYINT NULL DEFAULT 1 COMMENT '订单类型  1 普通订单',
  `order_source` TINYINT NULL DEFAULT 1 COMMENT '订单来源 1小程序 2 APP 3 第三方订单 4  H5',
  `order_price` DECIMAL(10,2) NULL DEFAULT '0' COMMENT '订单价格',
  `should_pay_price` DECIMAL(10,2) NULL COMMENT '应付金额',
  `actual_pay_price` DECIMAL(10,2) NULL DEFAULT '0' COMMENT '实付金额',
  `create_time` DATETIME NULL COMMENT '订单创建时间',
  `update_time` DATETIME NULL COMMENT '订单更新时间',
  `expire_time` DATETIME NULL COMMENT '订单过期时间',
  `pay_time` DATETIME NULL COMMENT '订单支付时间',
  `data_type` TINYINT NULL DEFAULT 1 COMMENT '数据类型 1 线上数据 2测试数据',
  `pay_type` TINYINT NULL DEFAULT 1 COMMENT '支付方式 1 微信 2 支付宝  3 云闪付',
  `update_user_id` BIGINT NULL DEFAULT -1 COMMENT '订单更新user_id',
  `pay_status` TINYINT NULL DEFAULT 1 COMMENT '支付状态 1 待支付 2 已支付',
  `transaction_status` TINYINT NULL DEFAULT 1 COMMENT '交易状态 1交易创建 2 交易关闭 3 交易成功',
  `evaluation_status` TINYINT NULL DEFAULT 1 COMMENT '评价状态 1待评价 2已评价',
  `order_status` TINYINT NULL DEFAULT 1 COMMENT '订单状态1待付款 2 待使用 3已取消 4已使用 5部分使用 6 退款中 7已退款 8 体验完成',
  `phone` VARCHAR(15) NULL DEFAULT '' COMMENT '订单联系人手机号',
  `tourist_name` VARCHAR(20) NULL DEFAULT '' COMMENT '客人姓名',
  `coupon_type` TINYINT NULL DEFAULT 1 COMMENT '优惠类型 1 不优惠 2 满减 3 优惠券 4 活动 ',
  `discount_price` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '优惠金额',
  `extra_information` TEXT NULL  COMMENT '附加信息  json字符串',
  `remark` VARCHAR(50) NULL DEFAULT '' COMMENT '订单备注',
  `is_delete` TINYINT NULL DEFAULT 1 COMMENT 'is_delete 逻辑删除字段。注释1未删除，2已删除',
  `pay_order_no` VARCHAR(50) NULL DEFAULT '' COMMENT '支付流水号',
  `three_member_id` BIGINT NULL COMMENT '第三方用户ID',
  `use_time` VARCHAR(50) NULL COMMENT '使用日期',
  CONSTRAINT `PK_order` PRIMARY KEY (`id` ASC)
)
  COMMENT = '订单表'

;

CREATE TABLE `request_log_month`
(
  `id` BIGINT NULL AUTO_INCREMENT COMMENT '主键',
  `method` VARCHAR(255) NULL COMMENT '请求地址',
  `request_body` TEXT NULL COMMENT '请求body',
  `request_headers` TEXT NULL COMMENT '请求头',
  `request_type` VARCHAR(50) NULL COMMENT '请求方式',
  `request_params` VARCHAR(255) NULL COMMENT '请求参数',
  `sender` VARCHAR(50) NULL COMMENT '请求ip',
  `response_body` TEXT NULL COMMENT '响应body',
  `response_headers` VARCHAR(50) NULL COMMENT '响应头',
  `response_status` VARCHAR(50) NULL COMMENT '响应状态',
  `create_time` DATETIME NULL COMMENT '创建时间'
)
  COMMENT = '订单微服务日志请求记录表,按照月份自动创建表'

;

CREATE TABLE `ticket_child`
(
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `start_place` INT NULL COMMENT '出发点id',
  `end_place` INT NULL COMMENT '到达点Id',
  `ticket_type` INT NULL COMMENT '票型ID 101成人票  203 儿童票  308 携童票',
  `line_id` INT NULL COMMENT '航线ID',
  `ship_id` INT NULL COMMENT '船舶Id',
  `start_time` VARCHAR(50) NULL COMMENT '开航时间',
  `ticket_price` DECIMAL(10,2) NULL COMMENT '票价',
  `cabin_id` VARCHAR(50) NULL COMMENT '航班船舱Id/航班信息',
  `name` VARCHAR(50) NULL COMMENT '游客姓名',
  `id_number` VARCHAR(50) NULL COMMENT '证件号码',
  `type` INT NULL COMMENT '证件类型 1 身份证',
  `baby_info` VARCHAR(50) NULL COMMENT '婴儿信息 名字加证件号 小红 41139XXXxxxxx',
  `refund_status` TINYINT NULL DEFAULT 1 COMMENT '退款状态 1 不退款 2 退款中 3 退款成功',
  `code` VARCHAR(50) NULL COMMENT '查询码',
  `ticket_password` VARCHAR(50) NULL COMMENT '取票密码',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  `order_id` BIGINT NULL COMMENT '订单Id',
  `order_no` VARCHAR(50) NULL COMMENT '订单号',
  `start_place_name` VARCHAR(50) NULL DEFAULT '' COMMENT '出发港名称',
  `end_place_name` VARCHAR(50) NULL DEFAULT '' COMMENT '到达港名称',
  `cabin_name` VARCHAR(50) NULL DEFAULT '',
  CONSTRAINT `PK_ticket_child` PRIMARY KEY (`id` ASC)
)
  COMMENT = '船票类订单子表'

;

SET FOREIGN_KEY_CHECKS=1
;


CREATE TABLE `withdraw_serial` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `c_date` date DEFAULT NULL COMMENT '日期',
  `serial` int(10) DEFAULT NULL COMMENT '今日已达流水号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='提现单序列号';


CREATE TABLE `withdraw_limit` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `money` double(11,2) DEFAULT NULL COMMENT '今日已提现订单金额',
  `times` int(10) DEFAULT NULL COMMENT '今日已提现订单次数',
  `c_date` date DEFAULT NULL COMMENT '日期',
  `distributor_id` bigint(20) DEFAULT NULL COMMENT '分销商ID',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='提现每日限额';


CREATE TABLE `withdraw_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `withdraw` varchar(60) DEFAULT NULL COMMENT '提现金额（使用Plain格式，保留两位小数）',
  `withdraw_total` varchar(60) DEFAULT NULL COMMENT '总共可提现金额（使用Plain格式，保留两位小数）',
  `permit` tinyint(1) DEFAULT '0' COMMENT '审批状态,-2: 未审核；1：已通过,-1：未通过',
  `withdraw_serial` varchar(60) DEFAULT NULL COMMENT '提现单号',
  `distribute_date_between` varchar(60) DEFAULT NULL COMMENT '分销日期，格式如下：2019-05-06/2019-12-08',
  `distributor_id` bigint(20) DEFAULT NULL COMMENT '分销商ID',
  `distributor_name` varchar(60) DEFAULT NULL COMMENT '分销商姓名',
  `distributor_cellphone` varchar(60) DEFAULT NULL COMMENT '分销商手机号',
  `distributor_account_num` varchar(60) DEFAULT NULL COMMENT '分销商账户号',
  `distributor_message` varchar(60) DEFAULT NULL COMMENT '分销商信息',
  `put_out` tinyint(1) DEFAULT '0' COMMENT '发放状态,-2:未发放；1：发放中；2：已发放',
  `put_out_user_id` bigint(20) DEFAULT NULL COMMENT '发放操作人',
  `put_out_user_name` varchar(60) DEFAULT NULL COMMENT '发放操作人姓名',
  `put_out_date_time` datetime DEFAULT NULL COMMENT '发放操作时间',
  `permit_user_id` bigint(20) DEFAULT NULL COMMENT '审批人ID',
  `permit_user_name` varchar(60) DEFAULT NULL COMMENT '审批人姓名',
  `permit_date_time` datetime DEFAULT NULL COMMENT '审批日期',
  `permit_comment` varchar(180) DEFAULT NULL COMMENT '审批备注',
  `orders_id` varchar(60) DEFAULT NULL COMMENT '订单ID使用半角逗号分隔',
  `distribute_status_updated` tinyint(1) DEFAULT '0' COMMENT '是否完成分销单状态更新',
  `orders_profit` varchar(90) DEFAULT NULL COMMENT '订单分成，使用半角逗号分隔，顺序与orders_id中的orderId保持一致',
  `distributor_account_type` tinyint(1) DEFAULT NULL COMMENT '分销商账户类型,0:微信；1：银行卡',
  `distributor_account_sign` varchar(60) DEFAULT NULL COMMENT '分销商账户标示，例：1002',
  `apply_date_time` datetime DEFAULT NULL COMMENT '申请时间',
  `distributor_account_user` varchar(60) DEFAULT NULL COMMENT '开户人姓名',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='提现记录';






