server:
  port: 9013
spring:
  application:
    name: promotions-service
  profiles:
    active: @profiles.active@
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: cn.enn.wise.uncs.base.config.SSOPDateFormat

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  global-config:
    db-config:
      logic-delete-field: isdelete  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 2 # 逻辑已删除值(默认为 2)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 1)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis:
  table:
    auto: update
  database:
    type: mysql
  model:
    pack: cn.enn.wise.ssop.service.promotions.model
  mapper-locations: classpath*:mapper/*Mapper.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  type-aliases-package: cn.enn.wise.ssop.service.promotions.bean,com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
log:
  path: ./log