server:
  port: 9013
  servlet:
    context-path: /mall-v1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
#      defaultZone: http://dev-eureka:9004/eureka/
#      defaultZone: http://test-eureka:9006/eureka/
#      defaultZone: http://prod-master:9001/eureka/,http://prod-backup:9002/eureka/
spring:
  application:
    name: wise.platform.mall
  rabbitmq:
    host: 10.38.128.83
    port: 5672
    username: test
    password: test
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true
    virtual-host: test
  redis:
    host: 10.38.128.83
    port: 6379
    timeout: 60s
    database: 1
    lettuce:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 5
        max-wait: -1
  # 数据源
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: guide
          password: guide
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://10.38.128.81:3306/nxj_mall?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=false
          druid: #以下均为默认值
            initial-size: 3
            max-active: 8
            min-idle: 2
            max-wait: -1
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            filters: stat,wall
            share-prepared-statements: true
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
        slave:
          username: guide
          password: guide
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://10.38.128.81:3306/nxj_mall?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=false
          druid: #以下均为默认值
            initial-size: 3
            max-active: 8
            min-idle: 2
            max-wait: -1
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            filters: stat,wall
            share-prepared-statements: true
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
  jackson:
    time-zone: GMT+8
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 10.38.128.204:9300
    mongodb:
      host: 10.38.128.83
      port: 27017
      database: admin
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  database:
    type: mysql
  model:
    pack: cn.enn.wise.platform.mall.bean.bo.autotable
  table:
    auto: update
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file: info.log


#自定义
wx:
  miniapp:
    configs:
      - appid: wx76453a21da3fe5b3
        secret: 6ad61553799a531009b39f4bc6787a4a
        token:
        aesKey:
        msgDataFormat: JSON
      - appid: wx73466b979c886373
        secret: 14bbded952712e3dab5818b1019c6f65
        token:
        aesKey:
        msgDataFormat: JSON
      - appid: wxc545473f261825b0
        secret: aaf4e6715e592827da020563082c8113
        token:
        aesKey:
        msgDataFormat: JSON

TOKEN_SERVICE_URL: http://genius.enn.cn/member-v1/login/getUserByToken

companyId: 13
# Http调用配置
url:
  hostprefix: http://genius.enn.cn/
  distributeBasePath: distribute-v1
  mallBasePath: mall-v1
  memberBasePath: member-v1
  bscPath: bsc-
  dxgPath: dxg-
  wzdPath: wzd-
  nxjPath: nxj-
urlconfig:
  urlConfigBeans:
  - companyId: 5
    urlMap:
      CHECKUSER_SERVICE_URL:  ${url.hostprefix}${url.dxgPath}${url.distributeBasePath}/distributeorder/checkuser
      SAVEDISTRIBUTEORDER_SERVICE_URL:  ${url.hostprefix}${url.dxgPath}${url.distributeBasePath}/app/distribute/order/save
      STAFF_TOKEN_URL:  ${url.hostprefix}${url.memberBasePath}/wisePlatform/getUserByToken
      CHECK_STRATEGY_URL: ${url.hostprefix}${url.dxgPath}${url.distributeBasePath}/app/distribute/checkstrategyitem
      UPDATE_STRATEGY_ITEM_BY_IS_SERVICE: ${url.hostprefix}${url.dxgPath}${url.distributeBasePath}/app/distribute/update/strategyitem/isservice
      OPENID_SERVICE_URL: ${url.hostprefix}${url.memberBasePath}/wx/openid
      scenic_service_url: ${url.hostprefix}/wzd-tourism-pandaro/encdata-pandaro/scenic/getCodes
      getDistributeByUserId: ${url.hostprefix}/${url.dxgPath}${url.distributeBasePath}/distributor/getbyuserid
      DISTRIBUTE_URL: ${url.hostprefix}${url.dxgPath}${url.distributeBasePath}
      GET_GOODSID_BYROLEID: ${url.hostprefix}${url.dxgPath}${url.distributeBasePath}/distributor/role/goodsid
      UPDATE_STRATEGY_ITEM: ${url.hostprefix}${url.dxgPath}${url.distributeBasePath}/app/distribute/strategy/update
      GET_MEMBER_INFO_URL: ${url.hostprefix}${url.memberBasePath}/member/head/imgurl
  - companyId: 7
    urlMap:
      CHECKUSER_SERVICE_URL:  ${url.hostprefix}${url.dxgPath}${url.distributeBasePath}/distributeorder/checkuser
      SAVEDISTRIBUTEORDER_SERVICE_URL:  ${url.hostprefix}${url.dxgPath}${url.distributeBasePath}/app/distribute/order/save
      STAFF_TOKEN_URL:  ${url.hostprefix}${url.memberBasePath}/wisePlatform/getUserByToken
      CHECK_STRATEGY_URL: ${url.hostprefix}${url.dxgPath}${url.distributeBasePath}/app/distribute/checkstrategyitem
      UPDATE_STRATEGY_ITEM_BY_IS_SERVICE: ${url.hostprefix}${url.dxgPath}${url.distributeBasePath}/app/distribute/update/strategyitem/isservice
      OPENID_SERVICE_URL: ${url.hostprefix}${url.memberBasePath}/wx/openid
      scenic_service_url: ${url.hostprefix}/wzd-tourism-pandaro/encdata-pandaro/scenic/getCodes
      getDistributeByUserId: ${url.hostprefix}/${url.dxgPath}${url.distributeBasePath}/distributor/getbyuserid
      DISTRIBUTE_URL: ${url.hostprefix}${url.dxgPath}${url.distributeBasePath}
      GET_GOODSID_BYROLEID: ${url.hostprefix}${url.dxgPath}${url.distributeBasePath}/distributor/role/goodsid
      UPDATE_STRATEGY_ITEM: ${url.hostprefix}${url.dxgPath}${url.distributeBasePath}/app/distribute/strategy/update
      GET_MEMBER_INFO_URL: ${url.hostprefix}${url.memberBasePath}/member/head/imgurl
  - companyId: 10
    urlMap:
      CHECKUSER_SERVICE_URL:  ${url.hostprefix}${url.bscPath}${url.distributeBasePath}/distributeorder/checkuser
      SAVEDISTRIBUTEORDER_SERVICE_URL:  ${url.hostprefix}${url.bscPath}${url.distributeBasePath}/app/distribute/order/save
      STAFF_TOKEN_URL:  ${url.hostprefix}${url.memberBasePath}/wisePlatform/getUserByToken
      CHECK_STRATEGY_URL: ${url.hostprefix}${url.bscPath}${url.distributeBasePath}/app/distribute/checkstrategyitem
      UPDATE_STRATEGY_ITEM_BY_IS_SERVICE: ${url.hostprefix}${url.bscPath}${url.distributeBasePath}/app/distribute/update/strategyitem/isservice
      OPENID_SERVICE_URL: ${url.hostprefix}${url.memberBasePath}/wx/openid
      scenic_service_url: ${url.hostprefix}/bsc-tourism-pandaro/encdata-pandaro/scenic/getCodes
      getDistributeByUserId: ${url.hostprefix}/${url.bscPath}${url.distributeBasePath}/distributor/getbyuserid
      DISTRIBUTE_URL: ${url.hostprefix}${url.bscPath}${url.distributeBasePath}
      GET_GOODSID_BYROLEID: ${url.hostprefix}${url.bscPath}${url.distributeBasePath}/distributor/role/goodsid
      UPDATE_STRATEGY_ITEM: ${url.hostprefix}${url.bscPath}${url.distributeBasePath}/app/distribute/strategy/update
      GET_MEMBER_INFO_URL: ${url.hostprefix}${url.memberBasePath}/member/head/imgurl
  - companyId: 11
    urlMap:
      CHECKUSER_SERVICE_URL:  ${url.hostprefix}${url.wzdPath}${url.distributeBasePath}/distributeorder/checkuser
      SAVEDISTRIBUTEORDER_SERVICE_URL:  ${url.hostprefix}${url.wzdPath}${url.distributeBasePath}/app/distribute/order/save
      STAFF_TOKEN_URL:  ${url.hostprefix}${url.memberBasePath}/wisePlatform/getUserByToken
      CHECK_STRATEGY_URL: ${url.hostprefix}${url.wzdPath}${url.distributeBasePath}/app/distribute/checkstrategyitem
      UPDATE_STRATEGY_ITEM_BY_IS_SERVICE: ${url.hostprefix}${url.wzdPath}${url.distributeBasePath}/app/distribute/update/strategyitem/isservice
      OPENID_SERVICE_URL: ${url.hostprefix}${url.memberBasePath}/wx/openid
      scenic_service_url: ${url.hostprefix}/wzd-tourism-pandaro/encdata-pandaro/scenic/getCodes
      getDistributeByUserId: ${url.hostprefix}/${url.wzdPath}${url.distributeBasePath}/distributor/getbyuserid
      DISTRIBUTE_URL: ${url.hostprefix}${url.wzdPath}${url.distributeBasePath}
      GET_GOODSID_BYROLEID: ${url.hostprefix}${url.wzdPath}${url.distributeBasePath}/distributor/role/goodsid
      UPDATE_STRATEGY_ITEM: ${url.hostprefix}${url.wzdPath}${url.distributeBasePath}/app/distribute/strategy/update
      GET_MEMBER_INFO_URL: ${url.hostprefix}${url.memberBasePath}/member/head/imgurl
      GET_PROJECT_INFO_LIST: ${url.hostprefix}wzd-tourism-pandaro/info/findActInfoListByTicketIdList
      GET_PROJECT_INFO: ${url.hostprefix}wzd-tourism-pandaro/info/findActInfoByTicketId
  - companyId: 13
    urlMap:
      CHECKUSER_SERVICE_URL:  ${url.hostprefix}${url.nxjPath}${url.distributeBasePath}/distributeorder/checkuser
      SAVEDISTRIBUTEORDER_SERVICE_URL:  ${url.hostprefix}${url.nxjPath}${url.distributeBasePath}/app/distribute/order/save
      STAFF_TOKEN_URL:  ${url.hostprefix}${url.memberBasePath}/wisePlatform/getUserByToken
      CHECK_STRATEGY_URL: ${url.hostprefix}${url.nxjPath}${url.distributeBasePath}/app/distribute/checkstrategyitem
      UPDATE_STRATEGY_ITEM_BY_IS_SERVICE: ${url.hostprefix}${url.nxjPath}${url.distributeBasePath}/app/distribute/update/strategyitem/isservice
      OPENID_SERVICE_URL: ${url.hostprefix}${url.memberBasePath}/wx/openid
      scenic_service_url: ${url.hostprefix}/nxj-tourism-pandaro/encdata-pandaro/scenic/getCodes
      getDistributeByUserId: ${url.hostprefix}/${url.nxjPath}${url.distributeBasePath}/distributor/getbyuserid
      DISTRIBUTE_URL: ${url.hostprefix}${url.nxjPath}${url.distributeBasePath}
      GET_GOODSID_BYROLEID: ${url.hostprefix}${url.nxjPath}${url.distributeBasePath}/distributor/role/goodsid
      UPDATE_STRATEGY_ITEM: ${url.hostprefix}${url.nxjPath}${url.distributeBasePath}/app/distribute/strategy/update
      GET_MEMBER_INFO_URL: ${url.hostprefix}${url.memberBasePath}/member/head/imgurl
      GET_PROJECT_INFO_LIST: http://tx.enn.cn/nxj-tourism-pandaro/info/findActInfoListByTicketIdList
      GET_PROJECT_INFO: http://tx.enn.cn/nxj-tourism-pandaro/info/findActInfoByTicketId
# 小程序授权登录配置
wxpay:
  wxPayConfig:
    # 西藏大峡谷小程序配置
    -  companyId: 5
       appId: wx73466b979c886373
       mchId: 1504256541
       key: 849f35d652f825eb7028369517ee1f87
       tradeType: JSAPI
       notifyUrl: http://genius.enn.cn/dxg-mall-v1/orders/wzd/complate
    -  companyId: 7
       appId: wx73466b979c886373
       mchId: 1504256541
       key: 849f35d652f825eb7028369517ee1f87
       tradeType: JSAPI
       notifyUrl: http://tx.enn.cn/dxg-mall-v1/orders/wzd/complate
    # 涠洲岛小程序配置
    -  companyId: 11
       appId: wx76453a21da3fe5b3
      #mchId: 1325029701
       mchId: 1559222021
      #       key: 91b147c700de21a6163ed68833903dd9
       key: 26b8a138d04a52631ba21e43e6e2b0e9
       tradeType: JSAPI
       notifyUrl: http://genius.enn.cn/wzd-mall-v1/orders/wzd/complate
    # 巴松措小程序配置
    - companyId: 10
      appId: wxc545473f261825b0
      mchId: 1528261671
      key: Xzlybsc600792019Xzlybsc600792019
      tradeType: JSAPI
      notifyUrl: http://genius.enn.cn/bsc-mall-v1/orders/wzd/complate
    # 涠洲岛船票支付商户主体
    - companyId: 101
      appId: wx76453a21da3fe5b3
      mchId: 1325029701
      #       mchId: 1559222021
      key: 91b147c700de21a6163ed68833903dd9
      #       key: 26b8a138d04a52631ba21e43e6e2b0e9
      tradeType: JSAPI
      notifyUrl: http://genius.enn.cn/wzd-mall-v1/orders/wzd/complate/ticket
  # 楠溪江小程序配置
    - companyId: 13
      appId: wx17727d2732e03351
      mchId: 1510696711
      key: ySEXoJBkZ8wurAQc6pJjzXRiK9nD6YR2
      tradeType: JSAPI
      notifyUrl: http://tx.enn.cn/nxj-mall-v1/orders/wzd/complate

# 队列配置
queueconfig:
  prefix: nxj.

audit:
  phone: 18611369632
  name: 小赵
  h5url: /mall-audith5/#/withdrawal
  refundH5Url: /mall-audith5/#/refund

bbd:
 SECRET_KEY: 20200107bbdsaveOfflineOrderKey195033



